CREATE TABLE demonstracoes_contabeis (
    DATA DATE NOT NULL,
    REG_ANS VARCHAR(50) NOT NULL,
    CD_CONTA_CONTABIL VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    VL_SALDO_INICIAL TEXT,
    VL_SALDO_FINAL TEXT,
    PRIMARY KEY (DATA, REG_ANS, CD_CONTA_CONTABIL)
);
