COPY demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
FROM 'C:/tmp/1T2023.csv' 
WITH (FORMAT csv, DELIMITER ';', HEADER true, QUOTE '"');

COPY demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
FROM 'C:/tmp/1T2024.csv' 
WITH (FORMAT csv, DELIMITER ';', HEADER true, QUOTE '"');

COPY demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
FROM 'C:/tmp/2t2023.csv' 
WITH (FORMAT csv, DELIMITER ';', HEADER true, QUOTE '"');

COPY demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
FROM 'C:/tmp/2T2024.csv' 
WITH (FORMAT csv, DELIMITER ';', HEADER true, QUOTE '"');

COPY demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
FROM 'C:/tmp/3T2023.csv' 
WITH (FORMAT csv, DELIMITER ';', HEADER true, QUOTE '"');

COPY demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
FROM 'C:/tmp/3T2024.csv' 
WITH (FORMAT csv, DELIMITER ';', HEADER true, QUOTE '"');

COPY demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
FROM 'C:/tmp/4T2023.csv' 
WITH (FORMAT csv, DELIMITER ';', HEADER true, QUOTE '"');

COPY demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
FROM 'C:/tmp/4T2024.csv' 
WITH (FORMAT csv, DELIMITER ';', HEADER true, QUOTE '"');